In [76]:
import csv
import pandas as pd
import pickle
from sklearn.model_selection import train_test_split
from sklearn import tree
from sklearn import svm
from sklearn import metrics
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
import numpy as np

In [47]:
dataset = pd.read_csv('data/dataset_full.csv')

print(dataset.columns)
print(dataset.shape)

Index(['qty_dot_url', 'qty_hyphen_url', 'qty_underline_url', 'qty_slash_url',
       'qty_questionmark_url', 'qty_equal_url', 'qty_at_url', 'qty_and_url',
       'qty_exclamation_url', 'qty_space_url',
       ...
       'qty_ip_resolved', 'qty_nameservers', 'qty_mx_servers', 'ttl_hostname',
       'tls_ssl_certificate', 'qty_redirects', 'url_google_index',
       'domain_google_index', 'url_shortened', 'phishing'],
      dtype='object', length=112)
(88647, 112)


In [48]:
dataset.isnull().any()

qty_dot_url             False
qty_hyphen_url          False
qty_underline_url       False
qty_slash_url           False
qty_questionmark_url    False
                        ...  
qty_redirects           False
url_google_index        False
domain_google_index     False
url_shortened           False
phishing                False
Length: 112, dtype: bool

In [49]:
train_data, test_data, train_labels, test_labels = train_test_split(
    dataset.iloc[:, 0:30], 
    dataset.iloc[:, -1], 
    test_size=0.2
)

In [50]:
train_data.shape, train_labels.shape, test_data.shape, test_labels.shape

((70917, 30), (70917,), (17730, 30), (17730,))

In [51]:
print(train_data)

       qty_dot_url  qty_hyphen_url  qty_underline_url  qty_slash_url  \
78238            2               0                  0              0   
51744            2               1                  1              4   
5118             1               3                  0              2   
77926            2               0                  0              0   
57191            2               0                  0              9   
...            ...             ...                ...            ...   
11257            2               0                  0              3   
17325            2               0                  0              0   
58805            2               0                  0              0   
9411             2               0                  0              1   
61205            1               0                  0              1   

       qty_questionmark_url  qty_equal_url  qty_at_url  qty_and_url  \
78238                     0              0           0          

In [52]:
dataset.iloc[:, -1]

0        1
1        1
2        0
3        1
4        0
        ..
88642    0
88643    0
88644    1
88645    1
88646    0
Name: phishing, Length: 88647, dtype: int64

In [53]:
clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_labels)

DecisionTreeClassifier()

In [54]:
pred_labels_val = cross_val_predict(clf, train_data, train_labels, cv=10)
conf_mat = confusion_matrix(train_labels, pred_labels_val)
print(conf_mat)

[[43701  2741]
 [ 3564 20911]]


In [55]:
pred_labels_test = clf.predict(test_data)

In [56]:
print("Accuracy:", metrics.accuracy_score(test_labels, pred_labels_test))      # Calculating the accuracy of the model
print("Precision:", metrics.precision_score(test_labels, pred_labels_test))    # Calculating the precision of the model
print("Recall:", metrics.recall_score(test_labels, pred_labels_test)) 

Accuracy: 0.9088550479413423
Precision: 0.8809364548494983
Recall: 0.8535320803629294


In [70]:
clf.predict([test_data.iloc[2773]])

array([0])

In [73]:
clf.predict(test_data.iloc[2773].values.reshape(1,-1))

array([0])

In [90]:
for i in range(1, 1000):
    l = test_data.iloc[i].values.tolist()
    print(clf.predict(np.array(l).reshape(1,-1)))

[0]
[1]
[0]
[0]
[1]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[1]
[1]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[0]
[0]
[1]
[0]
[1]
[1]
[0]
[0]
[1]
[0]
[0]
[1]
[1]
[0]
[0]
[0]
[0]
[1]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[1]
[0]
[1]
[0]
[0]
[0]
[0]
[1]
[0]
[1]
[1]
[0]
[1]
[1]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[1]
[1]
[1]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[1]
[0]
[1]
[0]
[0]
[1]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[1]
[0]
[0]
[1]
[0]
[0]
[1]
[1]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[0]
[1]
[0]
[1]
[1]
[0]
[0]
[0]
[0]
[0]
[0]
[1]
[1]
[0]
[0]
[0]
[1]
[1]
[1]
[1]
[0]
[0]
[0]
[0]
[1]
[1]
[0]
